name: Deploy VitePress to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build VitePress
        run: npm run build
      
      - name: Deploy to Cloudflare Pages
        run: |
          echo "Deploying to Cloudflare Pages..."
          echo "Project name: A6"
          
          # Check if project exists, create if not
          if ! npx wrangler pages project list 2>/dev/null | grep -q "A6"; then
            echo "Creating new Cloudflare Pages project: A6"
            npx wrangler pages project create A6 --production-branch=main
          else
            echo "Project A6 already exists"
          fi
          
          # Deploy to Cloudflare Pages
          npx wrangler pages deploy .vitepress/dist --project-name=A6 --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
